# Generated by Django 2.2.7 on 2019-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BT_Contact',
            fields=[
                ('Contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(default='Default_name', max_length=50)),
                ('Last_Name', models.CharField(default='Default_lastname', max_length=50)),
                ('Emailid', models.CharField(default='Default@email.com', max_length=100)),
                ('Message', models.CharField(default='No_Message', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sess_response', models.CharField(max_length=100)),
            ],
        ),
    ]
