# Generated by Django 2.1 on 2019-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_contact',
            name='Contact_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
