# Generated by Django 2.1 on 2019-11-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0002_auto_20191119_1455'),
        ('mydemoapp', '0002_auto_20191118_1659'),
    ]

    operations = [
    ]
