# Generated by Django 2.2.6 on 2019-11-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0003_merge_20191119_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_contact',
            name='Contact_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
