# Generated by Django 2.2.6 on 2019-12-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0005_auto_20191212_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='button_id',
            field=models.CharField(max_length=50),
        ),
    ]
