# Generated by Django 2.2.6 on 2019-12-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0009_bt_imageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_imageupload',
            name='Image',
            field=models.ImageField(blank=True, upload_to='Media/'),
        ),
    ]
