# Generated by Django 2.2.6 on 2019-12-29 06:25

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mydemoapp', '0010_auto_20191226_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bt_imageupload',
            name='Image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=100, size=[800, 800], upload_to='Media/'),
        ),
    ]
